### ISSUE TITLE
I'd appreciate a pianoroll mode like in GB Studio.

### ISSUE THREAD

**Issue by darkhog** [SuperDisk/hUGETracker#162]
It would be neat to have a pianoroll mode like in GB Studio. It's way easier and more fun to do songs that way, however I don't want to open GB Studio just to make some tunes. I'd appreciate a pianoroll interface in the Huge Tracker proper.

**Comment by SuperDisk** [comment]
I considered this at one point but I don't know if it's worth the effort. The piano roll interface is, in my opinion, only useful when onboarding people who've never used trackers before, since ultimately you'll need to switch to the tracker interface if you want to take full advantage of the hardware. For GB Studio it makes sense because it's where a lot of people get first introduced to composing for an old sound chip, but in hUGETracker I don't think it would add much value. And of course you can always just pop open GB Studio to use the piano roll even if you're not making a game with it.

I'll leave this open for now since I'm kind of considering exploring the idea anyway, but I don't think it will happen any time soon, sorry :(

**Comment by darkhog** [comment]
Think of it this way: The more people you could get using the software, the more popular it will get meaning it would get used in more games. Many people want to make chiptunes, but the trackers scare them away. I know, because I am such a person. Plus it's easier to "get" how long each note takes in a pianoroll as opposed to a tracker. not to mention it's even possible to visualize tracker effects automation. The problem with making authentic chiptunes is that there are too many trackers for that and too few (none?) that support modern workflows. You can get something that sounds like an old chiptune in something like LMMS or Ardour, but it won't be 100% authentic as those programs don't enforce the limits.

**Comment by SuperDisk** [comment]
Sorry, but HT is fundamentally a tracker and not a DAW. In my opinion (backed by experience) the tracker interface is better suited for old sound chips than piano rolls. While I acknowledge that people who've never used a tracker before would rather stick to what they know, ultimately you need to use the right tools for the job. In the same way that people would prefer to use C rather than assembly when programming for the GB, it gives you familiarity at the expense of the ability to fully utilize the hardware, because it's not a very good fit for the hardware.

Despite that, GB Studio provides a piano roll for newbies to get started with (but IMO it's only useful for newbies) so I won't duplicate that effort in HT. I do appreciate the input and suggestion, but this is just the way I see the situation.
